// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Category struct {
	CategoryID   int16          `json:"category_id"`
	CategoryName string         `json:"category_name"`
	Description  sql.NullString `json:"description"`
	Picture      []byte         `json:"picture"`
}

type Customer struct {
	CustomerID   interface{}    `json:"customer_id"`
	CompanyName  string         `json:"company_name"`
	ContactName  sql.NullString `json:"contact_name"`
	ContactTitle sql.NullString `json:"contact_title"`
	Address      sql.NullString `json:"address"`
	City         sql.NullString `json:"city"`
	Region       sql.NullString `json:"region"`
	PostalCode   sql.NullString `json:"postal_code"`
	Country      sql.NullString `json:"country"`
	Phone        sql.NullString `json:"phone"`
	Fax          sql.NullString `json:"fax"`
}

type CustomerCustomerDemo struct {
	CustomerID     interface{} `json:"customer_id"`
	CustomerTypeID interface{} `json:"customer_type_id"`
}

type CustomerDemographic struct {
	CustomerTypeID interface{}    `json:"customer_type_id"`
	CustomerDesc   sql.NullString `json:"customer_desc"`
}

type Employee struct {
	EmployeeID      int16          `json:"employee_id"`
	LastName        string         `json:"last_name"`
	FirstName       string         `json:"first_name"`
	Title           sql.NullString `json:"title"`
	TitleOfCourtesy sql.NullString `json:"title_of_courtesy"`
	BirthDate       sql.NullTime   `json:"birth_date"`
	HireDate        sql.NullTime   `json:"hire_date"`
	Address         sql.NullString `json:"address"`
	City            sql.NullString `json:"city"`
	Region          sql.NullString `json:"region"`
	PostalCode      sql.NullString `json:"postal_code"`
	Country         sql.NullString `json:"country"`
	HomePhone       sql.NullString `json:"home_phone"`
	Extension       sql.NullString `json:"extension"`
	Photo           []byte         `json:"photo"`
	Notes           sql.NullString `json:"notes"`
	ReportsTo       sql.NullInt16  `json:"reports_to"`
	PhotoPath       sql.NullString `json:"photo_path"`
}

type EmployeeTerritory struct {
	EmployeeID  int16  `json:"employee_id"`
	TerritoryID string `json:"territory_id"`
}

type Order struct {
	OrderID        int16           `json:"order_id"`
	CustomerID     interface{}     `json:"customer_id"`
	EmployeeID     sql.NullInt16   `json:"employee_id"`
	OrderDate      sql.NullTime    `json:"order_date"`
	RequiredDate   sql.NullTime    `json:"required_date"`
	ShippedDate    sql.NullTime    `json:"shipped_date"`
	ShipVia        sql.NullInt16   `json:"ship_via"`
	Freight        sql.NullFloat64 `json:"freight"`
	ShipName       sql.NullString  `json:"ship_name"`
	ShipAddress    sql.NullString  `json:"ship_address"`
	ShipCity       sql.NullString  `json:"ship_city"`
	ShipRegion     sql.NullString  `json:"ship_region"`
	ShipPostalCode sql.NullString  `json:"ship_postal_code"`
	ShipCountry    sql.NullString  `json:"ship_country"`
}

type OrderDetail struct {
	OrderID   int16   `json:"order_id"`
	ProductID int16   `json:"product_id"`
	UnitPrice float32 `json:"unit_price"`
	Quantity  int16   `json:"quantity"`
	Discount  float32 `json:"discount"`
}

type Product struct {
	ProductID       int16           `json:"product_id"`
	ProductName     string          `json:"product_name"`
	SupplierID      sql.NullInt16   `json:"supplier_id"`
	CategoryID      sql.NullInt16   `json:"category_id"`
	QuantityPerUnit sql.NullString  `json:"quantity_per_unit"`
	UnitPrice       sql.NullFloat64 `json:"unit_price"`
	UnitsInStock    sql.NullInt16   `json:"units_in_stock"`
	UnitsOnOrder    sql.NullInt16   `json:"units_on_order"`
	ReorderLevel    sql.NullInt16   `json:"reorder_level"`
	Discontinued    int32           `json:"discontinued"`
}

type Region struct {
	RegionID          int16       `json:"region_id"`
	RegionDescription interface{} `json:"region_description"`
}

type Shipper struct {
	ShipperID   int16          `json:"shipper_id"`
	CompanyName string         `json:"company_name"`
	Phone       sql.NullString `json:"phone"`
}

type Supplier struct {
	SupplierID   int16          `json:"supplier_id"`
	CompanyName  string         `json:"company_name"`
	ContactName  sql.NullString `json:"contact_name"`
	ContactTitle sql.NullString `json:"contact_title"`
	Address      sql.NullString `json:"address"`
	City         sql.NullString `json:"city"`
	Region       sql.NullString `json:"region"`
	PostalCode   sql.NullString `json:"postal_code"`
	Country      sql.NullString `json:"country"`
	Phone        sql.NullString `json:"phone"`
	Fax          sql.NullString `json:"fax"`
	Homepage     sql.NullString `json:"homepage"`
}

type Territory struct {
	TerritoryID          string      `json:"territory_id"`
	TerritoryDescription interface{} `json:"territory_description"`
	RegionID             int16       `json:"region_id"`
}

type UsState struct {
	EmployeeID  int16          `json:"employee_id"`
	StateName   sql.NullString `json:"state_name"`
	StateAbbr   sql.NullString `json:"state_abbr"`
	StateRegion sql.NullString `json:"state_region"`
}
