// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	CategoryID   int16       `json:"category_id"`
	CategoryName string      `json:"category_name"`
	Description  pgtype.Text `json:"description"`
	Picture      []byte      `json:"picture"`
}

type Customer struct {
	CustomerID   interface{}        `json:"customer_id"`
	CompanyName  string             `json:"company_name"`
	ContactName  pgtype.Text        `json:"contact_name"`
	ContactTitle pgtype.Text        `json:"contact_title"`
	Address      pgtype.Text        `json:"address"`
	City         pgtype.Text        `json:"city"`
	Region       pgtype.Text        `json:"region"`
	PostalCode   pgtype.Text        `json:"postal_code"`
	Country      pgtype.Text        `json:"country"`
	Phone        pgtype.Text        `json:"phone"`
	Fax          pgtype.Text        `json:"fax"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Active       pgtype.Bool        `json:"active"`
}

type CustomerCustomerDemo struct {
	CustomerID     interface{} `json:"customer_id"`
	CustomerTypeID interface{} `json:"customer_type_id"`
}

type CustomerDemographic struct {
	CustomerTypeID interface{} `json:"customer_type_id"`
	CustomerDesc   pgtype.Text `json:"customer_desc"`
}

type Employee struct {
	EmployeeID      int16              `json:"employee_id"`
	LastName        string             `json:"last_name"`
	FirstName       string             `json:"first_name"`
	Title           pgtype.Text        `json:"title"`
	TitleOfCourtesy pgtype.Text        `json:"title_of_courtesy"`
	BirthDate       pgtype.Date        `json:"birth_date"`
	HireDate        pgtype.Date        `json:"hire_date"`
	Address         pgtype.Text        `json:"address"`
	City            pgtype.Text        `json:"city"`
	Region          pgtype.Text        `json:"region"`
	PostalCode      pgtype.Text        `json:"postal_code"`
	Country         pgtype.Text        `json:"country"`
	HomePhone       pgtype.Text        `json:"home_phone"`
	Extension       pgtype.Text        `json:"extension"`
	Photo           []byte             `json:"photo"`
	Notes           pgtype.Text        `json:"notes"`
	ReportsTo       pgtype.Int2        `json:"reports_to"`
	PhotoPath       pgtype.Text        `json:"photo_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Active          pgtype.Bool        `json:"active"`
}

type EmployeeTerritory struct {
	EmployeeID  int16  `json:"employee_id"`
	TerritoryID string `json:"territory_id"`
}

type Order struct {
	OrderID        int16         `json:"order_id"`
	CustomerID     interface{}   `json:"customer_id"`
	EmployeeID     pgtype.Int2   `json:"employee_id"`
	OrderDate      pgtype.Date   `json:"order_date"`
	RequiredDate   pgtype.Date   `json:"required_date"`
	ShippedDate    pgtype.Date   `json:"shipped_date"`
	ShipVia        pgtype.Int2   `json:"ship_via"`
	Freight        pgtype.Float4 `json:"freight"`
	ShipName       pgtype.Text   `json:"ship_name"`
	ShipAddress    pgtype.Text   `json:"ship_address"`
	ShipCity       pgtype.Text   `json:"ship_city"`
	ShipRegion     pgtype.Text   `json:"ship_region"`
	ShipPostalCode pgtype.Text   `json:"ship_postal_code"`
	ShipCountry    pgtype.Text   `json:"ship_country"`
}

type OrderDetail struct {
	OrderID   int16   `json:"order_id"`
	ProductID int16   `json:"product_id"`
	UnitPrice float32 `json:"unit_price"`
	Quantity  int16   `json:"quantity"`
	Discount  float32 `json:"discount"`
}

type Product struct {
	ProductID       int16         `json:"product_id"`
	ProductName     string        `json:"product_name"`
	SupplierID      pgtype.Int2   `json:"supplier_id"`
	CategoryID      pgtype.Int2   `json:"category_id"`
	QuantityPerUnit pgtype.Text   `json:"quantity_per_unit"`
	UnitPrice       pgtype.Float4 `json:"unit_price"`
	UnitsInStock    pgtype.Int2   `json:"units_in_stock"`
	UnitsOnOrder    pgtype.Int2   `json:"units_on_order"`
	ReorderLevel    pgtype.Int2   `json:"reorder_level"`
	Discontinued    int32         `json:"discontinued"`
}

type Region struct {
	RegionID          int16       `json:"region_id"`
	RegionDescription interface{} `json:"region_description"`
}

type Shipper struct {
	ShipperID   int16       `json:"shipper_id"`
	CompanyName string      `json:"company_name"`
	Phone       pgtype.Text `json:"phone"`
}

type Supplier struct {
	SupplierID   int16       `json:"supplier_id"`
	CompanyName  string      `json:"company_name"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactTitle pgtype.Text `json:"contact_title"`
	Address      pgtype.Text `json:"address"`
	City         pgtype.Text `json:"city"`
	Region       pgtype.Text `json:"region"`
	PostalCode   pgtype.Text `json:"postal_code"`
	Country      pgtype.Text `json:"country"`
	Phone        pgtype.Text `json:"phone"`
	Fax          pgtype.Text `json:"fax"`
	Homepage     pgtype.Text `json:"homepage"`
}

type Territory struct {
	TerritoryID          string      `json:"territory_id"`
	TerritoryDescription interface{} `json:"territory_description"`
	RegionID             int16       `json:"region_id"`
}

type UsState struct {
	EmployeeID  int16       `json:"employee_id"`
	StateName   pgtype.Text `json:"state_name"`
	StateAbbr   pgtype.Text `json:"state_abbr"`
	StateRegion pgtype.Text `json:"state_region"`
}
